spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pw44s
    username: postgres
    password: 5432
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false